name: deploy api to deploys.app
on:
  push:
    branches:
      - main
    paths-ignore:
      - web
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: asia-southeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: cmd/api/Dockerfile
          push: true
          tags: asia.gcr.io/scamo-group/abdul-gg/epx5-api-service
    outputs:
      image: asia.gcr.io/scamo-group/abdul-gg/epx5-api-service@${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: deploys-app/deploys-action@v1
        with:
          project: abdul-gg
          location: gke.cluster-rcf2
          name: epx5-api-service
          image: ${{ needs.build.outputs.image }}
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}